print lobby settings in game tab
BitCrackers/AmongUsMenu pull request #334
Opened 2022-04-05 02:49 UTC by kotae4

* closes BitCrackers/AmongUsMenu#301

2022-04-05 05:49 UTC, cddjr requested changes

2022-04-05 05:49 UTC, cddjr commented on gui/tabs/game_tab.cpp
> +				ImGui::Dummy(ImVec2(7, 7));
scaling by dpi.
ex. ImGui::Dummy(ImVec2(xxxx) * State.dpiScale);

2022-04-06 02:14 UTC, cddjr approved these changes

2022-04-06 04:32 UTC, v0idp approved these changes

2022-04-06 04:32 UTC, merged